# Generated by Django 4.2.4 on 2023-08-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness_hour',
            name='store_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store_data',
            name='store_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store_status',
            name='store_id',
            field=models.CharField(max_length=255),
        ),
    ]
